openapi: 3.0.0
info:
  title: Аренда ресурсов облачного сервиса
  version: 0.0.1
sevrers:
  - url: http://lockalhost:8080/api/v1/
    description: Dev servers
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурсов на облако
      tags:
        - Clouds
      operationId: getAllClouds
      responses: 
        "200":
          description: Успешный ответ на запрос
          content: 
            aplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Все остальное
          content:
            aplication/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Создание заказа на облако
      tags: 
        - Clouds
      operationId: createCloud
      requestBody:
        content:
          aplication/json:
            schema:
              $ref: "#/components/schemas/Clouds"
      responses:
        "200":
          description: Успешный ответ на запрос
          content: 
            aplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Все остальное
          content:
            aplication/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cloud/{cloudId}:
    delete:
      summary: Отмена заказа по ID
      tags:
        - Clouds
      operationId: canselCloudById
      parameters:
        - name: cloudId
          in: path
          required: true
          description: Id заказа на облако
          schema: 
            type: string
          example: f123j5678
      responses:
        "200":
          description: Отмена прошла успешно
          content:
             aplication/json: {}
        "404":
           description: Заказ не найден
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error"
        "default":
          description: Все остальное
          content:
            aplication/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cloud/{clientId}/{RAM}:
    put:
      summary: Изменение арендуемого обьема памяти
      tags:
        - Clouds
      parameters: 
        - name: clientId
          in: path
          required: true
          description: Id клиента
          schema: 
            type: string
          example: f123j5678
        - name: RAM
          in: path
          required: true
          description: изменение объема памяти
          schema:
             type: integer
          example: 516
      operationId: changeCloud
      requestBody:
        content:
          aplication/json:
            schema:
              $ref: "#/components/schemas/Clouds"
      responses:
        "200":
           description: Успешное изменение обьема памяти
           content:
             adplication/json: {}
        "404":
           description: ClientId не найден
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error"
        "default":
           description: Все остальные ответы
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error"
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_client
        - OS
        - RAM
        - CPU
        - SSD
      properties:
        cloudId:
          type: string
          example: f1234j5678
        clientId:
          type: string
          example: f1234j5678
        OS: 
          type: string
          enum:
            - Windows
            - Linux
        RAM:
          type: integer
          example: 256
        CPU:
          type: string
          example: 4
        SSD:
          type: string
          example: 1024
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message: 
          type: string
          
